# Generated by Django 4.1.6 on 2023-03-12 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Facebook friends'),
        ),
    ]
