# Generated by Django 4.1.6 on 2023-03-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Media title')),
                ('plot', models.TextField(blank=True, verbose_name='Plot')),
                ('language', models.CharField(blank=True, max_length=30, verbose_name='Language')),
                ('region', models.CharField(blank=True, max_length=30, verbose_name='Region')),
                ('runtime', models.CharField(blank=True, max_length=30, verbose_name='Runtime')),
                ('awards', models.TextField(blank=True, verbose_name='Awards')),
                ('type', models.CharField(blank=True, choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=15, verbose_name='Type')),
                ('box_office', models.CharField(blank=True, max_length=50, verbose_name='Box Office')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Director')),
                ('writers', models.TextField(blank=True, verbose_name='Writers')),
                ('cast', models.TextField(blank=True, verbose_name='Cast')),
                ('banner', models.URLField(blank=True, max_length=255, verbose_name='Banner')),
                ('trailer_link', models.URLField(blank=True, verbose_name='Trailer link')),
                ('initial_release', models.IntegerField(blank=True, null=True, verbose_name='Initial release date')),
                ('final_release', models.IntegerField(blank=True, null=True, verbose_name='Final release date')),
                ('user_rating', models.FloatField(blank=True, default=0, verbose_name='User rating')),
                ('rating_count', models.IntegerField(blank=True, default=0, verbose_name='Rating count')),
                ('watch_count', models.IntegerField(blank=True, default=0, verbose_name='Watch count')),
                ('ratings', models.JSONField(blank=True, default=dict, verbose_name='Ratings')),
                ('imdb_id', models.CharField(blank=True, max_length=30, verbose_name='Imdb ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Extra')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='User rating')),
                ('review', models.TextField(blank=True, verbose_name='User review')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.media', verbose_name='Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Media',
                'verbose_name_plural': 'User Medias',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('medias', models.ManyToManyField(to='medias.media', verbose_name='Movies')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
    ]
