# Generated by Django 4.1.6 on 2023-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='language',
            field=models.CharField(blank=True, max_length=60, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='media',
            name='region',
            field=models.CharField(blank=True, max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='media',
            name='runtime',
            field=models.CharField(blank=True, max_length=50, verbose_name='Runtime'),
        ),
    ]
