# Generated by Django 4.1.6 on 2023-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='awards',
            field=models.TextField(blank=True, verbose_name='Awards'),
        ),
        migrations.AddField(
            model_name='media',
            name='box_office',
            field=models.CharField(blank=True, max_length=50, verbose_name='Box Office'),
        ),
        migrations.AlterField(
            model_name='media',
            name='final_release',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final release date'),
        ),
        migrations.AlterField(
            model_name='media',
            name='initial_release',
            field=models.IntegerField(blank=True, null=True, verbose_name='Initial release date'),
        ),
    ]
