# Generated by Django 4.1.6 on 2023-03-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_alter_media_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='region',
            field=models.CharField(blank=True, max_length=250, verbose_name='Region'),
        ),
    ]
